### ISSUE TITLE
cache xmake using @actions/cache

### ISSUE THREAD

**Issue by ZhUyU1997** [xmake-io/github-action-setup-xmake#16]
### Is your feature request related to a problem? Please describe.

@actions/tool-cache can't provide a stable caching strategy.
Refer to: https://github.com/actions/toolkit/issues/58#issuecomment-521672239
I prefer to replace it with @actions/cache.

### Describe the solution you'd like

For compatibility, we can add a new configuration field to control the cache folder.
If not set, still use @actions/tool-cache as before

```yaml
            - uses: xmake-io/github-action-setup-xmake@v1
              with:
                  xmake-version: "2.7.2"
                  actions-cache-folder: ".xmake-cache"
```

### Additional context

Reference:
- https://github.com/mymindstorm/setup-emsdk#cache
