### ISSUE TITLE
CI Warning: Cache Service Responded with 422 When Using xmake Cache

### ISSUE THREAD

**Issue by shuc1** [xmake-io/github-action-setup-xmake#39]
### Xmake Version

2.9.9

### Operating System Version and Architecture

GitHub Actions runner OS: windows-latest

### Describe Bug

When using the following GitHub Actions step, the action log reports the warning: `Warning: Failed to restore: Cache service responded with 422`.
```yml
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: ${{ runner.os }}
          build-cache: true
          build-cache-key: ${{ runner.os }}
          package-cache: true
          package-cache-key: ${{ runner.os }}
          project-path: ${{ github.workspace }}
```

### Expected Behavior

The cache should restore successfully without warnings.

### Project Configuration

1. Add the above step to a GitHub Actions workflow.
2. Run the workflow.
3. Observe the warning in the action log.

### Additional Information and Error Logs

Everything else is functioning correctly; only the warning is displayed. I am wondering if this issue is related to the [@actions/cache Package Deprecation Notice. Upgrade to the latest 4.0.0 or higher before February 1st 2025](https://github.com/actions/toolkit/discussions/1890)

Any insights or suggestions for resolving this warning would be appreciated.
