### ISSUE TITLE
Cache service still responds with 422

### ISSUE THREAD

**Issue by ripel2** [xmake-io/github-action-setup-xmake#41]
### Xmake Version

2.9.9

### Operating System Version and Architecture

Github Actions ubuntu-latest / windows-latest

### Describe Bug

Even after PR #39, we still get the `Failed to restore: Cache service responded with 422` error when using the action.

### Expected Behavior

The cache should restore succesfully without warnings

### Project Configuration

Minimal reproducible example (can be found in  [ripel2/xmake-action-test](https://github.com/ripel2/xmake-action-test))
```yaml
name: ci

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
      - 'gh-pages'

jobs:
  test_ci:
    name: Build and verify binaries
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest changes
        run: git pull origin ${{ github.ref_name }}

      - name: Setup Linux dependencies
        if: contains(runner.os, 'windows') == false
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev mesa-utils

      - name: Setup Windows dependencies
        if: contains(runner.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1.1.9
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: '${{ runner.os }}-xmake-install'
          package-cache: true
          package-cache-key: '${{ runner.os }}-xmake-entt-glm'
          project-path: '.'

      - name: Build project
        run: xmake build -y
        timeout-minutes: 8

      - name: Try to run the project
        run: |
          xmake run
```

### Additional Information and Error Logs

See latest runs of either [ripel2/xmake-action-test](https://github.com/ripel2/xmake-action-test/actions) or [EngineSquared/EngineSquared](https://github.com/EngineSquared/EngineSquared/actions)

![Image](https://github.com/user-attachments/assets/2ba7b695-ef08-495d-a832-c8b7be46d5b1)

![Image](https://github.com/user-attachments/assets/08a27be4-b568-4577-a8d9-dbf1f842cf8b)

Doesn't work either with `xmake-io/github-action-setup-xmake@v1.1.9` or `xmake-io/github-action-setup-xmake@master`
